project:
  type: default

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    fig-width: 12
    fig-height: 6
    self-contained: true

execute:
  freeze: auto
  warning: false
  echo: true

author: Mykyta
